### ISSUE TITLE
Regarding Trouble Running Project: .NET 8 Error Seeking Version Lower Than 8, Yet I Have Installed Version 7

### ISSUE THREAD

**Issue by MDarde** [H4x0rModdz/RansomSharp#1]
I'm currently trying to run the project and rebuild it, but I keep getting an error. It seems to be unhappy because I had downloaded the latest version of .NET 8, then uninstalled it, and even restarted my computer. When I tried again, I still got the same error, which says it needs a version lower than the eighth, and I have downloaded the seventh. Can you please guide me on what to do?

**Comment by H4x0rModdz** [comment]
You're experiencing an issue with the version even when using .NET 8? LOL... Well, I think I can add a release to see if the problem persists for you because it's working perfectly fine here, you know? My bad for taking so long, I was in touch with other projects and didn't check the notifications. You can go to the releases and download it; it should probably work correctly. If it doesn't, let me know.
